name: Deploy to production

on:
  push:
    branches: [ develop ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    name: SCP files to server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@develop
      - name: SCP files via ssh key
        uses: appleboy/scp-action@develop
        with:
          username: ${{ secrets.REMOTE_USER }}
          host: ${{ secrets.REMOTE_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: './*.js'
          target: '/home/alexwolf/sinusbot/botdata/scripts'
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: curl "https://sinusbot.alexwolf.ru/auth/${{ secrets.EVENTNAME }}"
