name: SCP Files Action

on:
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  scp-files-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: a-was/scp-action@v1
        with:
          # Remote host
          host: ${{ secrets.REMOTE_HOST }}
          # Remote host SSH port. Default 22
          port: 22
          # Remote host user
          user: ${{ secrets.REMOTE_USER }}
          # SSH private key
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # Repo directory path. Default whole repo
          source: '$(pwd)/*'
          # Remote directory path. Default home directory (~/)
          destination: '/home/alexwolf/sinusbot/botdata/scripts'
