name: Deploy to production

on:
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    name: SCP files to server
    runs-on: ubuntu-latest
    steps:
      - name: SCP files via ssh key
        uses: appleboy/scp-action@master
        env:
          USERNAME: ${{ secrets.REMOTE_USER }}
          HOST: ${{ secrets.REMOTE_HOST }}
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source: './*'
          target: '/home/alexwolf/sinusbot/botdata/scripts'
