name: Deploy to production

on:
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    name: SCP files to server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: SCP files via ssh key
        uses: appleboy/scp-action@master
        with:
          username: ${{ secrets.REMOTE_USER }}
          host: ${{ secrets.REMOTE_HOST }}
 #         key: ${{ secrets.SSH_PRIVATE_KEY }}
          password: ${{ secrets.PASSWORD }}
          source: './*'
          target: '/home/alexwolf/sinusbot/botdata/scripts'
